name = "vibecreative"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-05"

[env.production]
name = "vibecreative" 

[env.preview]
name = "vibecreative-preview"

# Environment variables will be set in the Cloudflare Pages dashboard
# GMAIL_SENDER
# GMAIL_TO
# GMAIL_CLIENT_ID
# GMAIL_CLIENT_SECRET
# GMAIL_REFRESH_TOKEN
# ALLOWED_ORIGIN 