name = "booking-email-worker"
main = "functions/booking-email.ts"
compatibility_date = "2024-09-05"

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" } 