name = "vibe-designs"
pages_build_output_dir = "out"
compatibility_date = "2024-09-05"

[env.production]

[env.preview]

# Environment variables will be set in the Cloudflare Pages dashboard
# GMAIL_SENDER
# GMAIL_TO
# GMAIL_CLIENT_ID
# GMAIL_CLIENT_SECRET
# GMAIL_REFRESH_TOKEN
# ALLOWED_ORIGIN 